sudo: required

arch:
  - arm64

matrix:
  include:
    - os: linux
      arch: arm64

services:
  - docker

script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  
  # Specify dockerhub (or any registry) repo
  - docker build --tag ${DOCKER_USERNAME}/${REPO} .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    # Specify github branch used to build
    branch: ${BRANCH}
